version: "3.8"
services: #se indican que servicios se van a utilizar
    nodered: #Empezar NodeRed
        container_name: Nodered #Nombramos el contenedor
        image: nodered/node-red:latest #Indicamos la imagen de la cual e creara el contenedor
        restart: always #Para que se inicie en automatico sin que se detenga
        ports:
            - 1880:1880 #Asignacion de puerto
        depends_on:
            - influx

    influxdb: #Empezar InfluxDB
        container_name: InfluxDB #Nombramos el contenedor
        image: influxdb #Indicamos la imagen de la cual e creara el contenedor
        restart: always #Para que se inicie en automatico sin que se detenga
        environment: #Asignacion de usuario y contraseña
            - INFLUXDB_DB=grafana
            - INFLUXDB_USER=grafana
            - INFLUXDB_USER_PASSWORD=password
            - INFLUXDB_ADMIN_ENABLE=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=password

    grafana: #Empieza Grafana
        container_name: Grafana #Nombramos el contenedor
        image: grafana/grafana #Indicamos la imagen de la cual e creara el contenedor
        restart: always #Para que se inicie en automatico sin que se detenga
        ports:
            - 3000:3000 #asigacion de puerto
        depends_on: #Agregamos la base de datos de la cual va a depender
            - influxdb
        environment: #Asignacion de usuario y contraseña
            - GF_SECURITY_ADMIN_USER=user
            - GF_SECURITY_ADMIN_PASSWORD=1234
            - GRAFANA_INFLUX_DB=influxdb
            - GRAFANA_INFLUX_USER=user
            - GRAFANA_INFLUX_PASSWORD=1234
